/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bbscool_BaiduPCS */

#ifndef _Included_cn_bbscool_BaiduPCS
#define _Included_cn_bbscool_BaiduPCS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    pcs_who
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bbscool_BaiduPCS_pcs_1who
  (JNIEnv *, jobject);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    cmd_quota
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bbscool_BaiduPCS_cmd_1quota
  (JNIEnv *, jobject);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    pcs_upload
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_pcs_1upload
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    pcs_login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_pcs_1login
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    pcs_logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_pcs_1logout
  (JNIEnv *, jobject);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    cmd_setjobid
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_cmd_1setjobid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_bbscool_BaiduPCS
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bbscool_BaiduPCS_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
